R/BackendCbind.R, R/BackendRbind.R, R/Experiment.R, R/Learner.R, R/PredictionClassif.R, R/PredictionRegr.R, R/ResampleResult.R, R/Resampling.R, R/Task.R, R/TaskClassif.R, R/TaskRegr.R, R/helper_misc.R, R/mlr_learners_classif_dummy.R, R/mlr_learners_regr_dummy.R, R/mlr_resamplings_cv.R, man/Task.Rd, man/TaskClassif.Rd, man/TaskRegr.Rd, tests/testthat/helper.R, tests/testthat/test_Backend.R, tests/testthat/test_Task.R, tests/testthat/test_TaskClassif.R, tests/testthat/test_mlr_learners_classif_dummy.R, tests/testthat/test_mlr_learners_regr_dummy.R, tests/testthat/test_train_predict_score.R
* more checks to cbind/rbind tasks
* col_info and row_info should now be updated properly
=> Factor handling

DESCRIPTION, R/Experiment.R, R/options.R, R/resample.R, README.md, vignettes/basic-04-parallelization.Rmd
Keep the dependencies minimal.
=> Move future to suggests

vignettes/basic-03-resample-benchmarking.Rmd
I don't think the plotting of the resulting rpart model adds any value here. 
Also the img was cut at the top and therefore did not look very professional.
=> Update and rename resample/benchmarking vignette

R/Resampling.R, R/assertions.R, R/mlr_resamplings_bootstrap.R, R/mlr_resamplings_cv.R, R/mlr_resamplings_holdout.R, R/mlr_resamplings_repeated_cv.R, R/mlr_resamplings_subsampling.R, docs/articles/basic-05-error-handling.html, tests/testthat/test_Resampling.R, vignettes/basic-05-error-handling.Rmd
=> enable param checks

R/Experiment.R, R/PredictionClassif.R, R/PredictionRegr.R, R/Resampling.R, R/Task.R, R/Task_mutators.R, docs/articles/basic-01-tasks.html, docs/reference/Task.html, inst/testthat/helper_expectations.R, man/Task.Rd, tests/testthat/test_DataBackendCbind.R, tests/testthat/test_PredictionClassif.R, tests/testthat/test_PredictionRegr.R, tests/testthat/test_Task.R
Was a data.table, now is an atomic vector.
=> Change return value of task$row_ids

R/Learner.R
GraphLearner needs param_set to be an active binding
=> make param_set an AB of Learner

R/MeasureClassifCosts.R, R/Task_mutators.R
Current changes that would apply to master using the most recent version of the style guide.
=> Apply style guide to master

.Rbuildignore, README.Rmd, README.md
Can someone check if this is sufficient?
=> Add example to README

.gitmodules, .travis.yml, tic.R
Too many problems for the gain of having a centralized `tic.R` file :(
=> revert git submodule approach

inst/testthat/helper_autotest.R
=> Check for responses only if predict_type is response

R/TaskRegr.R, man/TaskRegr.Rd
in response to https://github.com/mlr-org/mlr3/issues/416
=> fix docs mistake in TaskRegr (closes issue #416)

NEWS.md, R/worker.R, tests/testthat/test_Learner.R
=> Handle empty predict sets

README.Rmd, README.md
=> Fix typo in readme

inst/testthat/helper_autotest.R, tests/testthat/test_mlr_learners_classif_rpart.R, tests/testthat/test_mlr_learners_regr_rpart.R
So that mlr3learners can make use of it from a central place.
=> Add `run_paramtest()` to helper_autotest.R

R/auto_convert.R
related: https://github.com/mlr-org/mlr3proba/issues/109
=> Fix typo in auto_convert numeric -> integer

inst/testthat/helper_autotest.R
see  mlr3learners/mlr3learners.partykit#5
=> add prob_vector_to_matrix as helper function

inst/testthat/helper_autotest.R
=> add replicability param

NEWS.md, R/DataBackendCbind.R, R/Resampling.R, R/ResamplingBootstrap.R, R/ResamplingCV.R, R/ResamplingHoldout.R, R/ResamplingInsample.R, R/ResamplingRepeatedCV.R, R/ResamplingSubsampling.R, R/Task.R, R/TaskClassif.R, man/Task.Rd, man/TaskClassif.Rd, tests/testthat/test_Task.R
Some cleanups to pave the road towards forcasting tasks.
=> Better support for ordered Tasks

R/Resampling.R, tests/testthat/test_mlr_resampling_bootstrap.R
=> Repair grouped ResamplingBootstrap

.github/workflows/tic.yml, .travis.yml
Also includes out lintr which was not yet included in this repo.
=> Run CI only on Ubuntu and remove branch builds

DESCRIPTION, NEWS.md, R/zzz.R
Originally this: https://github.com/mlr-org/mlr3/pull/509 but moved it to mlr3misc
=> Leanify with misc

R/mlr_sugar.R, man/mlr_sugar.Rd
There might be more similar instances for simplifying sugar examples.
=> Simplify `lrns()` example

R/BenchmarkResult.R, R/Learner.R, R/ResultData.R, R/Task.R, R/assertions.R, R/benchmark.R, R/resample.R, inst/testthat/helper_expectations.R, man/Learner.Rd, man/ResultData.Rd, man/as_result_data.Rd, man/benchmark.Rd, man/resample.Rd, tests/testthat/test_Learner.R
=> Null backend in result containers

R/benchmark.R, R/resample.R, R/zzz.R, man/mlr3-package.Rd, tests/testthat/test_benchmark.R, tests/testthat/test_resample.R
=> Debug mode

R/PredictionDataClassif.R, R/benchmark_grid.R, inst/testthat/helper_expectations.R, man/benchmark_grid.Rd
=> Fix for new class level during predict

NEWS.md, R/Task.R, R/mlr_reflections.R, man/Task.Rd, tests/testthat/test_Task.R
=> Remove col role 'uri'

NEWS.md, R/Learner.R, R/Task.R, inst/testthat/helper_expectations.R, man/Task.Rd, man/TaskClassif.Rd, man/TaskRegr.Rd, man/TaskSupervised.Rd, man/TaskUnsupervised.Rd, tests/testthat/test_Task.R
=> Column labels

R/TaskClassif.R, R/helper.R, tests/testthat/test_TaskClassif.R
=> Assert that target is encoded as factor in TaskClassif

R/benchmark.R, R/resample.R, macro.R, man-roxygen/param_encapsulate.R, man-roxygen/param_store_backends.R, man-roxygen/param_store_models.R, man/benchmark.Rd, man/resample.Rd
=> Make encapsulation more convenient

R/Resampling.R, R/partition.R, man/Resampling.Rd, man/partition.Rd, tests/testthat/test_mlr_resampling_cv.R
=> Add example to generate complex partitions

R/ResamplingCustomCV.R, R/Task.R, R/mlr_reflections.R, R/worker.R, man-roxygen/field_predict_sets.R, man-roxygen/param_predict_sets.R, man/BenchmarkResult.Rd, man/Learner.Rd, man/Measure.Rd, man/MeasureClassif.Rd, man/MeasureRegr.Rd, man/MeasureSimilarity.Rd, man/ResultData.Rd, man/Task.Rd, man/as_prediction.Rd, tests/testthat/test_DataBackendCbind.R, tests/testthat/test_Resampling.R, tests/testthat/test_Task.R
=> refactor: Rename validation -> holdout

R/Learner.R, R/Measure.R, R/Resampling.R, R/Task.R, R/TaskGenerator.R
=> fix: ability to print objects wo label 

R/LearnerClassifRpart.R, R/LearnerRegrRpart.R, man/mlr_learners_classif.rpart.Rd, man/mlr_learners_regr.rpart.Rd
https://github.com/mlr-org/mlr3learners/issues/252
=> docs: correct names for init param values

NEWS.md, R/ResultData.R
=> fix: reassembling of graph learners

R/DataBackendCbind.R, R/DataBackendMatrix.R, inst/testthat/helper_expectations.R, tests/testthat/test_Task.R, tests/testthat/test_convert_task.R
=> Fix return of task->missings being unnamed

R/as_prediction_classif.R, tests/testthat/test_PredictionClassif.R
=> Fix as_predcition_classif for data.frame()

R/Task.R, R/mlr_reflections.R, man/mlr_reflections.Rd
=> Extend task printer to customize col role printing

R/Task.R
=> Improve task printer to include additional row roles

R/as_task_classif.R, R/as_task_regr.R, man/as_task_regr.Rd, tests/testthat/test_as_task.R
=> Improve error messages for as_task_xx 

R/ResamplingHoldout.R, R/ResamplingInsample.R, man/mlr_resamplings_holdout.Rd, man/mlr_resamplings_insample.Rd
Solves https://github.com/mlr-org/mlr3/issues/923
=> fix: make resampling iters for holdout and subsampling read-only

NEWS.md, R/worker.R
Fixes https://github.com/mlr-org/mlr3/issues/972
=> fix: triggering fallback is now info

R/BenchmarkResult.R, R/ResampleResult.R, R/as_prediction.R, R/mlr_reflections.R, inst/testthat/helper_expectations.R, man/BenchmarkResult.Rd, man/ResampleResult.Rd, tests/testthat/test_benchmark.R, tests/testthat/test_mlr_reflections.R, tests/testthat/test_resample.R
=> Refactor: avoid confusing predict_set arg in  functions

R/LearnerRegr.R, R/as_measure.R, man/LearnerRegr.Rd, man/as_measure.Rd
mlr3website is failing because of this
=> add clone to as_measure(s) generic

R/LearnerRegr.R, man/LearnerRegr.Rd
closes: https://github.com/mlr-org/mlr3/issues/1246
=> docs(learner): add docs for quantile predict type

NEWS.md, R/BenchmarkResult.R, inst/testthat/helper_expectations.R, tests/testthat/test_benchmark.R
=> feat(bmr): Include ID columns when converting bmr to data.table

R/assertions.R, tests/testthat/test_Task.R
closes https://github.com/mlr-org/mlr3/issues/1285
=> fix: implicit type conversion of `task$row_roles$use`

R/Learner.R, R/PredictionData.R, R/PredictionDataClassif.R, R/Task.R, R/TaskClassif.R, R/TaskRegr.R, R/assertions.R, R/helper_data_table.R, R/mlr_reflections.R, R/task_converters.R, tests/testthat/test_Task.R, tests/testthat/test_helper_data_table.R
=> fix: levels are returned in correct order

tests/testthat/test_benchmark.R, tests/testthat/test_errorhandling.R, tests/testthat/test_resample.R
=> tests: suppress future warnings

R/BenchmarkResult.R, R/Learner.R, R/Measure.R, R/ResampleResult.R, R/Resampling.R, R/Task.R, man/BenchmarkResult.Rd, man/Learner.Rd, man/Measure.Rd, man/ResampleResult.Rd, man/Resampling.Rd, man/Task.Rd
=> docs: Add examples to methods

R/Learner.R, R/MeasureOOBError.R, R/worker.R, tests/testthat/test_Learner.R
=> feat: store oob error on state without storing models

.github/workflows/dev-cmd-check.yml, .github/workflows/no-suggest-cmd-check.yml, .github/workflows/pkgdown.yml, .github/workflows/r-cmd-check.yml, R/PredictionData.R, tests/testthat/test_backward_compatibility.R
=> fix: attribute handling
