- R/mlr_tasks.R
- tests/testthat/test_Dictionary.R
`!nzchar(find.package(package, quiet = TRUE))` returns an empty vector when the `package` is not installed. It causes a non-informative error message in `load_dataset`:
```
Error in if (!nzchar(find.package(package, quiet = TRUE))) stopf("Please install package '%s' for data set '%s'",  : 
argument is of length zero 
```
It might be better to change this to:
```
!length(find.package(package, quiet = TRUE))
```
> Throw a proper error when the package with dataset is missing

- tic.R
The installation step of deps was recently outsourced from the rcmdcheck step so that "less magic" is going on behind the scenes. Hence we need to explicitly specify it now.
Soon we will we able to use a one-line macro instead of chaining all these steps manually.
> Fix travis

- inst/trigger-mlr3book.sh
- tic.R
This change triggers a run of mlr3book on every successful Travis run on the master branch.
The mlr3book build will include the repo slug and the commit message so that we quickly see if a change in one of the repos triggered a failure of the book.
I described the heuristics in the [CI setup](https://www.notion.so/mlrorg/CI-setup-98e90e1eba044ff5ba576f2ffad768dc).
> Trigger mlr3book CI run on every successful master build

- .Rbuildignore
- .gitmodules
- .travis.yml
Served from https://github.com/mlr-org/mlr-ci/.
- Updated in every CI build
- Adds ability to update the CI of all mlr3 repos via one submodule commit
- the `--remote` options ensures that always the latest state of the master branch of the submodule is fetched in every CI build (by default it would always be the current state of the respective repo containing the submodule)
> Move tic.R to submodule

- .travis.yml
Officially supported by Travis now and marked as "stable": https://docs.travis-ci.com/user/reference/linux/#using-ubuntu-linux-distributions
> Travis: Build on bionic instead of xenial

- R/ResamplingCustom.R
- tests/testthat/test_benchmark.R
Adresses the bug #451.
Apparently `self$task_nrow` was not set.
I think it is not optimal to not call `super$instantiate()` because all changes on `Resample$instantiate()` have to be copied here.
But `Resampling$instantiate()` relies on `private$.sample()` which we than had to *fake* for `ResamplingCustom` which also sounds weird.
> set task_nrow in custom resampling (Fixes #451)

- inst/testthat/helper_autotest.R
* `all.equal.data.table` returns `character` instead of `FALSE`
* Fix seed
> Fix all.equal and seed bug in run_autotest

- R/LearnerClassifDebug.R
- tests/testthat/test_benchmark.R
- tests/testthat/test_mlr_learners_classif_debug.R
A small test that checks wheter `future::plan` enables prallelization correctly for `benchmark()`. The change of the *debug learner* also would allow tests for correct parallelization in more complicated setups.
Note: There might be conflict once [this branch](https://github.com/mlr-org/mlr3/tree/test-future) should be merged, because it uses future to parallelize the tests.
> Testing parallelization

- R/assertions.R
- R/worker.R
fixes https://github.com/mlr-org/mlr3learners/issues/72
AFAICS all other calling functions (resample, benchmark()) call `assert_learnable()` already.
With this PR:
``` r
library(mlr3)
library(mlr3learners)
lrn("classif.log_reg")$properties
#> [1] "twoclass" "weights"
tsk("iris")$properties
#> [1] "multiclass"
lrn("classif.log_reg")$train(tsk("iris"))
#> Error: <TaskClassif:iris> has the following unsupported properties: multiclass
```
<sup>Created on 2020-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
> Check for task/learner properties in `assert_learnable()`

- R/Learner.R
- R/assertions.R
- tests/testthat/test_Learner.R
What failed?
- `$predict_newdata` without y column for a learner that does not support missings
https://github.com/mlr-org/mlr3/blob/893611d497b2299765ccc338d8f16f6108caf85d/tests/testthat/test_Learner.R#L134-L139
Why?
- We called `assert_learnable()` (questionable name here) when calling `$predict` which checked ALL columns if there are missings.
Note: Another fix would be to just change `miss = task$missings()` to `miss = task$missings(cols = task$feature_names)` but then we still have the weird naming of `assert_learnable()` for prediction. Also we probably never ever want to allow missing y in `train()`?
> fix predict newdata

- R/BenchmarkResult.R
- R/Learner.R
- R/LearnerClassifDebug.R
- R/MeasureDebug.R
- R/PredictionDataClassif.R
- R/ResampleResult.R
- R/ResamplingHoldout.R
- R/ResultData.R
- R/Task.R
- R/TaskClassif_penguins.R
- R/TaskGeneratorMoons.R
- R/TaskSupervised.R
- R/as_prediction_data.R
- R/assertions.R
- R/auto_convert.R
- R/benchmark_grid.R
- R/bibentries.R
- R/default_measures.R
- R/mlr_resamplings.R
- R/task_converters.R
- R/worker.R
- tests/testthat/test_Learner.R
- tests/testthat/test_PredictionClassif.R
- tests/testthat/test_PredictionDataClassif.R
- tests/testthat/test_Resampling.R
- tests/testthat/test_Task.R
- tests/testthat/test_TaskClassif.R
- tests/testthat/test_benchmark.R
- tests/testthat/test_convert_task.R
- tests/testthat/test_hashes.R
This is a first diff of the new {[mlr.styler](https://github.com/mlr-org/styler.mlr)} package (still private) by @lorenzwalthert.
Lorenz put a [lot of time](https://github.com/mlr-org/styler.mlr/pull/1) into our mlr-style, not only by creating this new package but also in the past.
It should make updating + maintenance more easy and should also serve as an exemplary package for additional styles next to the `tidyverse_style`.
Beforehand we used a [fork of mine](https://github.com/pat-s/styler/tree/mlr-style).
@mllg I am not sure if you use {styler} in practice for {mlr3} but your input on specific re-occurring patterns which are changed in the diff is appreciated.
Remember that we can create the style guide to be passive/non-invasive so that in some cases multiple solutions are allowed / …
> Style package with new {mlr.styler} package

- DESCRIPTION
- R/ResamplingCustomCV.R
- R/helper.R
- man/mlr_resamplings_custom_cv.Rd
- tests/testthat/test_Resampling.R
- tests/testthat/test_mlr_resampling_custom.R
- tests/testthat/test_mlr_tasks.R
#651 
@mllg I've found `custom_cv$instantiate(task, split = split_f)` nicer to read than `custom_cv$instantiate(task, f = split_f)`. Feel free to change back if you disagree.
`ResamplingCustomCV` now accepts either an external factor or a feature from the task.
> Update `ResamplingCustomCV` and add tests

- R/DataBackendCbind.R
- R/DataBackendRbind.R
- R/Learner.R
- man/Learner.Rd
- tests/testthat/test_Learner.R
> Let Learner$predict_newdata() work on DataBackends

- R/benchmark.R
The learners in `benchmark()` must be cloned for each resampling iteration when hotstarting. We only clone per experiment. Test data is leaked into the hotstarted models. We should fix this soon.
The unit test should probably go into mlr3learners because of the `xgboost` dependency.
```r
task = tsk("pima")
learner_1 = lrn("classif.xgboost", nrounds = 100, predict_type = "prob")
resampling = rsmp("cv", folds = 3)
resampling$instantiate(task)
rr = resample(task, learner_1, resampling, store_models = TRUE)
stack = HotstartStack$new(rr$learners)
learner_2 = lrn("classif.xgboost", nrounds = 200, predict_type = "prob", hotstart_stack = stack)
bmr_1 = benchmark(benchmark_grid(task, learner_2, resampling))
bmr_2 = benchmark(benchmark_grid(task, learner_2, resampling), allow_hotstart = TRUE) …
```
> clone hotstart learner

- R/as_task_classif.R
- R/as_task_regr.R
The latest version does not work with `data.table()`.
```r
data = tsk("pima")$data()
as_task_classif(data, target = "diabetes")
Error in `[.data.table`(x, map_lgl(x, is.double)) : 
i evaluates to a logical vector length 9 but there are 768 rows. Recycling of logical i is no longer allowed as it hides more bugs than is worth the rare convenience. Explicitly use rep(...,length=.N) if you really need to recycle.
```
> fix inf check in task construction

- R/install_pkgs.R
Or at least, it looks like this is obsolete (since the assignment_linter is dropped in mlr3's .lintr config)
> remove obsolete # nolint

- DESCRIPTION
- R/PredictionData.R
- R/assertions.R
- R/benchmark.R
- R/mlr_reflections.R
- man/mlr_learners_classif.debug.Rd
- man/mlr_learners_classif.featureless.Rd
- man/mlr_learners_classif.rpart.Rd
- man/mlr_learners_regr.debug.Rd
- man/mlr_learners_regr.featureless.Rd
- man/mlr_learners_regr.rpart.Rd
- man/mlr_measures_aic.Rd
- man/mlr_measures_classif.costs.Rd
- man/mlr_measures_classif.fbeta.Rd
- man/mlr_measures_debug.Rd
- man/mlr_measures_selected_features.Rd
- man/mlr_task_generators_2dnormals.Rd
- man/mlr_task_generators_cassini.Rd
- man/mlr_task_generators_circle.Rd
- man/mlr_task_generators_friedman1.Rd
- man/mlr_task_generators_moons.Rd
- man/mlr_task_generators_simplex.Rd
- man/mlr_task_generators_smiley.Rd
- man/mlr_task_generators_spirals.Rd
- man/mlr_task_generators_xor.Rd
- tests/testthat/test_benchmark.R
- tests/testthat/test_mlr_reflections.R
* A learner type can now work with different task types e.g.  `LearnerClassif` with `TaskClassif` and `TaskClassifST`
* Assertions between task and learner or task and measure are performed on classes instead of `task_type` (`mlr_reflections$task_types`)
* prediction data class is part of `mlr_reflections$task_types` now
* mlr3cluster - https://github.com/mlr-org/mlr3cluster/pull/23 
* mlr3proba - https://github.com/mlr-org/mlr3proba/pull/286
* mlr3spatial - main branch depends on this PR
* mlr3spatiotempcv - https://github.com/mlr-org/mlr3spatiotempcv/pull/207
> refactor: additional task types in mlr_reflections

- NEWS.md
- R/Learner.R
- R/Task.R
- R/helper_hashes.R
- R/mlr_reflections.R
- R/worker.R
- tests/testthat/test_mlr_learners_classif_debug.R
* Rows with the `"test"` role are held back like rows with the `"holdout"` role.
* Rows are available to the learner in the `$.train` method
* Can be used e.g. by XGBoost for early stopping
* While resampling, the test set is automatically placed in the `"test"` role 
* While training, the test set must be set in the task by the user
```r
task = tsk("iris")
task$set_row_roles(1:10, roles = "test")
learner = lrn("classif.debug", save_tasks = TRUE)
learner$train(task)
learner$model$task_train$row_roles
#> $use
#>   [1]  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
#>  [29]  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66
#>  [57]  67  68  69  70  71  72  73  74 …
```
> feat: pass test set to train method

- NEWS.md
- R/MeasureElapsedTime.R
- tests/testthat/test_Measure.R
See here: https://stackoverflow.com/questions/73797845/mlr3-benchmarking-with-elapsed-time-measure
> fix: elapsed time returned 0

- inst/testthat/helper_expectations.R
when creating row_number() in mlr3db::as_duckdb_backend.character this is a bigint that is converted to a R numeric. When used in a Task, this makes the expect_task fail
> fix: duckdb backend has numeric row roles

- tests/testthat/test_errorhandling.R
Which now correctly distinguishes between NA_real_ and NaN
> Fix tests for dev waldo

- NEWS.md
- R/benchmark_grid.R
- man/benchmark_grid.Rd
- tests/testthat/test_benchmark.R
This was already available in mlr3oml under the name `benchmark_grid_oml()`, but is generally useful.
> feat: add argument `paired` to `benchmark_grid()`

- R/Learner.R
- R/LearnerClassifDebug.R
- R/resample.R
- R/worker.R
- inst/testthat/helper_expectations.R
- man-roxygen/param_unmarshal.R
- man/benchmark.Rd
- man/mlr_learners_classif.debug.Rd
- man/resample.Rd
- tests/testthat/test_Learner.R
- tests/testthat/test_marshal.R
- tests/testthat/test_resample.R
Summary: 
* setting `unmarshal = FALSE` not ensures that all models are in unmarshaled form (`resample()`, `benchmark()`). This is just easier to reason about 
* models are now also marshaled for prediction, i.e. for callr encapsulation and parallel prediction (I made a wrong assumption + somehow did not properly test this assumption)
* the marshaling of models for prediction happens automatically during `Learner$predict()`, but the model will be restored to its state before prediction. 
* the logic for the marshaling in the worker was refactored and is now much easier to understand 
* The `LearnerClassifDebug` now got an argument called `check_pid` that is `FALSE` by default. If this is set to `TRUE`, the `unmarshal_model()` method for `model_classif_debug` sets the `marshal_pid` slot of …
> feat(marshaling): also marshal during predict

- R/mlr_sugar.R
otherwise weird stuff can happen with partial arguments matching `dict` (e.g. `lrn("<id>, d = 10)`).
> fix: specify argument `dict` in dictionary getter explicitly

- tests/testthat/test_benchmark.R
- tests/testthat/test_resample.R
This functionality is essentially the same as for resample() where there are also the same tests, so this can be removed
Fixes #1083
> tests: remove unneded marshaling test

- NEWS.md
- R/LearnerClassifDebug.R
- R/LearnerRegrDebug.R
- man/Measure.Rd
- man/MeasureClassif.Rd
- man/MeasureRegr.Rd
- man/MeasureSimilarity.Rd
- man/mlr_learners_classif.debug.Rd
- man/mlr_learners_regr.debug.Rd
- man/mlr_measures_regr.pinball.Rd
- tests/testthat/test_mlr_learners_classif_debug.R
- tests/testthat/test_mlr_learners_regr_debug.R
> feat: classif.debug, regr.debug: add methods "importance" and  "selected_features"

- DESCRIPTION
- inst/testthat/helper_expectations.R
- tests/testthat/test_DataBackendRbind.R
- tests/testthat/test_Learner.R
- tests/testthat/test_Measure.R
- tests/testthat/test_Task.R
- tests/testthat/test_as_learner.R
- tests/testthat/test_benchmark.R
- tests/testthat/test_encapsulate.R
- tests/testthat/test_hashes.R
- tests/testthat/test_lgr.R
- tests/testthat/test_marshal.R
- tests/testthat/test_resample.R
- tests/testthat/test_warn_deprecated.R
use the following testthat functions:
- `expect_null()`
- `expect_length()`
- `expect_match()`
- `expect_no_warning()`
- `expect_no_error()`
- `expect_identical()`
> tests: use more specialised testthat functions

- R/DataBackendRename.R
- R/HotstartStack.R
- R/LearnerClassifDebug.R
- R/LearnerClassifRpart.R
- R/LearnerRegrRpart.R
- R/Measure.R
- R/PredictionClassif.R
- R/PredictionDataClassif.R
- R/PredictionDataRegr.R
- R/PredictionRegr.R
- R/Task.R
- R/assertions.R
- R/benchmark.R
- R/resample.R
- R/set_validate.R
- R/worker.R
- tests/testthat/test_HotstartStack.R
- tests/testthat/test_PredictionRegr.R
- tests/testthat/test_Task.R
- tests/testthat/test_benchmark.R
- tests/testthat/test_convert_task.R
- tests/testthat/test_resample.R
Not sure if this is wanted, but adds minor performance improvements. See the mini benchmark from data.table: https://rdatatable.gitlab.io/data.table/reference/chmatch.html#ref-examples. For small vectors it might not make much sense.
> perf: use `data.table::%chin%`

- R/Learner.R
- R/assertions.R
@sebffischer there is also [base::chkDots](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/chkDots), but only throws a warning. Maybe its generic enough to move this assertion to checkmate.
> refactor: simplify dots assertion

- inst/testthat/helper_expectations.R
For time series I don't want to check for strata in resampling, since its not supported.
> tests: make the strata check optional for resampling helper

- NEWS.md
- R/worker.R
- tests/testthat/test_Learner.R
> fix(marshaling): extract internal tuning info before marshaling

- R/Task.R
- tests/testthat/test_Task.R
For tasks in mlr3torch, `$data()` can cause downloads of large files, but it should be possible to construct tasks without downloading the data (e.g. for as.data.table(mlr_tasks)).
> fix(task): don't call $data() unnecessarily

- DESCRIPTION
Changes the min R version to 3.3 to reflect the min version used by data.table.
> chore: bump R version to 3.3

- .gitignore
- R/Learner.R
- R/Resampling.R
- R/ResamplingCustom.R
- R/Task.R
- R/assertions.R
- R/benchmark.R
- R/benchmark_grid.R
- R/resample.R
- R/worker.R
- man/Resampling.Rd
- man/Task.Rd
- man/benchmark_grid.Rd
- man/mlr_assertions.Rd
- tests/testthat/test_Resampling.R
- tests/testthat/test_Task.R
- tests/testthat/test_benchmark.R
- tests/testthat/test_resample.R
* Calling `task$filter(1:5)` removes rows from the task but `$train(task, row_ids = 6:10)` and `$predict(task, row_ids = 6:10)`  still use the removed row ids
* Calling `resampling$instantiate(task)` and `task$filter(1:5)` results in a similar error where `resample()` uses the removed row ids `6:10`
* `benchmark_grid()` allows to pass multiple tasks with the same number of rows and one or more resamplings instantiated on one of the tasks. Passing `task_1$filter(1:5)` and `task_2$filter(6:10)` with `resampling$instantiate(task_1)` is allowed but the resampling on `task_2` will use the removed row ids `1:5`.
* When creating the the design manually with `data.table()`, `benchmark()` does not check that the row ids of the resampling are present in the task.
* `task$filter()` allows to add and …
> fix: resamplings access removed rows

- inst/testthat/helper_autotest.R
This PR fixes an issue in the autotest (`helper_autotest`) where error messages were constructed using `sprintf(info, ...)` within the `err()` function. This caused tests to fail when error messages contained unescaped "%" characters (e.g., from matrix multiplication or other operations that return messages with "%" symbols).
Remove "%" characters from the info string (= error message) before passing it to `sprintf()`.
> fix: sprintf in autotest
